TechBuzzy_project/TechBuzzy_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls',namespace='account')),
    path('account/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('post.urls',namespace='post')),
]

TechBuzzy_project/post/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.PostCreateView.as_view(),name='create'),
    path('by/<username>/',views.UserPostList.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetailView.as_view(),name='single'),
    path('delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete'),
]

TechBuzzy_project/post/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from groups.models import Groups


User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now=True)
    message = models.TextField()
    group = models.ForeignKey(Groups,related_name='posts',null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_on']
        unique_together = ['user','message']

TechBuzzy_project/post/forms.py
from django import forms
from . import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

TechBuzzy_project/post/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse_lazy,reverse
from django.views import generic
from braces.views import SelectRelatedMixin
from django.http import Http404
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from . import models
from . import forms

User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user','group')
    template_name = 'post/post_list.html'

class UserPostList(generic.ListView):
    model = models.Post
    template_name = 'post/user_post_list.html'

    # Now get the queryset of post of current user and take from all posts
    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetailView(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')
    template_name = 'post/post_detail.html'

    # Collecting all post of current user from all post
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class PostCreateView(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    model = models.Post
    fields = ('group','message')
    template_name = 'post/post_form.html'

    def form_valid(self, form):
        # request.user typically returns an instance of django.contrib.auth.models.User, although the behavior depends on the authentication policy being used.
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class PostDeleteView(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')
    template_name = 'post/post_confirm_delete.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args, **kwargs):
        messages.success(self.request,'Post deleted successfully !')
        return super().delete(*args, **kwargs)

TechBuzzy_project/post/templates/post/_post.html
<div class="media">
    <h1 class="mr-5"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a> </h1>

    <div class="media-body">
        <h3><strong>{{post.user.username}}</strong></h3>
        <h4>{{post.message|safe}}
            <br>
            <small>
            <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"><i>{{post.created_on}}</i></a> </time>
            {% if post.group %}
            <span class="group_name">in <a href="#"><em>{{post.group.name}}</em></a></span>
            </small>
                {% endif %}
</h4>
        <div class="media-footer">
            {% if user.is_authenticated and post.user == user and not hide_delete %}
            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-warning">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
            </a>
            {% endif %}
        </div>
    </div>
</div>

TechBuzzy_project/post/templates/post/post_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <br><br><br>
    {% block pre_post %}{% endblock %}
    {% block post_content %}{% endblock %}
    {% block post_post %}{% endblock %}
</div>

{% endblock %}

TechBuzzy_project/post/templates/post/post_confirm_delete.html
{% extends 'post/post_base.html' %}
{% block post_content %}
<style>
    .del{
     box-shadow: 0 15px 25px rgba(0,0,0,.6);
     color:white;
     padding: 20px 20px 20px 20px;
     border-radius: 10px;
     width:700px;
     background: rgba(0,0,0,.5);
     position:relative;
     right:15%;
     box-sizing: border-box;
     font-family: 'Varela Round', serif;
     }
</style>
    <div class="del">

    <h3>Are you sure you want to delete post?</h3>
        <br>
    <div class="posts">
        {% include 'post/_post.html' with post=object hide_delete=True %}
    </div>
        <br>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
    </form>
    </div>


{% endblock %}

TechBuzzy_project/post/templates/post/post_detail.html
{% extends 'post/post_base.html' %}
{% block post_content %}
<style>
    .del{
     box-shadow: 0 15px 25px rgba(0,0,0,.6);
     color:white;
     padding: 20px 20px 20px 20px;
     border-radius: 10px;
     width:700px;
     background: rgba(0,0,0,.5);
     position:relative;
     right:15%;
     font-family: 'Varela Round', serif;
     box-sizing: border-box;
    }
</style>
    <div class="del">
    {% include 'post/_post.html' %}
    </div>
{% endblock %}

TechBuzzy_project/post/templates/post/post_form.html
{% extends 'post/post_base.html' %}
{% load bootstrap4 %}
{% block post_content %}
<div class="postform">
    <h3 class="title">Create Post</h3>
    <form method="POST" action="{% url 'posts:create' %}" class="formtext">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-success btn-large">Post</button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

TechBuzzy_project/post/templates/post/post_list.html
{% extends "post/post_base.html" %}

{% block pre_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">

				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %} #}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>

		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  		{% include "post/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

TechBuzzy_project/post/templates/post/user_post_list.html
{% extends 'post/post_base.html' %}
{% block pre_post %}
<style>
    .groupcontent{
     box-shadow: 0 15px 25px rgba(0,0,0,.6);
     padding: 20px 20px 20px 20px;
     border-radius: 10px;
     width:400px;
     background: rgba(0,0,0,.5);
     box-sizing: border-box;
     color:white;
     position:absolute;
     top:10%;
     left:10%;
     font-family: 'Varela Round', serif;
}

</style>
<div class="groupcontent">
    <div class="col-md-4">
        <h1>@{{post_user.username}}</h1>
        <p>Post History</p>
    </div>
</div>
{% endblock %}

{% block post_content %}
<style>
    .list{
     box-shadow: 0 15px 25px rgba(0,0,0,.6);
     padding: 20px 20px 20px 20px;
     border-radius: 10px;
     width:1000px;
     background: rgba(0,0,0,.5);
     box-sizing: border-box;
     color:white;
     position:absolute;
     top:30%;
     left:10%;
}
</style>
<div class="list">
    <div class="col-md-8">
        {% for post in post_list %}
            {% include 'post/_post.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}