TechBuzzy_project/TechBuzzy_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls',namespace='account')),
    path('account/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('post.urls',namespace='post')),
]

TechBuzzy_project/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('',views.GroupList.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.GroupDetail.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),
]

TechBuzzy_project/post/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.PostCreateView.as_view(),name='create'),
    path('by/<username>/',views.UserPostList.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetailView.as_view(),name='single'),
    path('delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete'),
]

TechBuzzy_project/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model

from django import template
register = template.Library()


User = get_user_model()

class Groups(models.Model):
    name = models.CharField(max_length=30,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    members = models.ManyToManyField(User,related_name='mem',through='GroupMember')

    def __str__(self):
        return self.name

    # Here override save in midel.Model
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Metal:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Groups,related_name='membership',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

TechBuzzy_project/groups/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views import generic
from groups.models import Groups,GroupMember
from django.db import IntegrityError
from django.contrib import messages
from . import models

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    model = Groups
    fields = ['name','description']
    template_name = 'groups/group_form.html'

class GroupDetail(generic.DetailView):
    model = Groups
    template_name = 'groups/group_detail.html'

class GroupList(generic.ListView):
    model = Groups
    template_name = 'groups/group_list.html'

class JoinGroup(generic.RedirectView, LoginRequiredMixin):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(models.Groups,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user = self.request.user, group=group )
        except IntegrityError:
            messages.warning(self.request,"Warning, already a member of {}".format(group.name))
        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))
        return super().get(request,*args,**kwargs)

class LeaveGroup(generic.RedirectView, LoginRequiredMixin):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(group__slug=self.kwargs.get('slug')).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,"You can't leave this group because you aren't in it.")
        else:
            membership.delete()
            messages.success(self.request,"You have successfully left this group.")

        return super().get(request, *args, **kwargs)

TechBuzzy_project/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-fluid">
        <br><br><br>
        <div class="row">
            {% block pregroup %}{% endblock %}
            {% block groupcontent %}{% endblock %}
            {% block postgroup %}{% endblock %}
        </div>
    </div>

{% endblock %}

TechBuzzy_project/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<style>
    .groupcontent{
     box-shadow: 0 15px 25px rgba(0,0,0,.6);
     padding: 20px 20px 20px 20px;
     border-radius: 10px;
     width:400px;
     background: rgba(0,0,0,.5);
     box-sizing: border-box;
     text-color:white;
     position:absolute;
     left:10%;
     font-family:  serif;
     color:white;
     font-family: 'Varela Round', serif;
}
</style>
<div class="groupcontent">
<div class="contianer">
    <h1>{{groups.name}}</h1>
    <h3>Members :{{groups.members.count}}</h3>
    <div class="content">
        {% if user in groups.members.all %}
        <a href="{% url 'groups:leave' slug=groups.slug %}" class="btn btn-lg btn-warning"><span class="fa fa-times-circle-o"></span>Leave</a>
        {% else %}
        <a href="{% url 'groups:join' slug=groups.slug %}" class="btn btn-lg btn-success"><span class="fa fa-check-circle-o"></span>Join</a>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

{% block groupcontent %}
<style>
    .groupcon{
     box-shadow: 0 15px 25px rgba(0,0,0,.6);
     padding: 20px 20px 20px 20px;
     border-radius: 10px;
     width:1000px;
     background: rgba(0,0,0,.5);
     box-sizing: border-box;
     text-color:white;
     position:absolute;
     left:40%;
     color:white;
     font-family: 'Varela Round', serif;
}
</style>

<div class="groupcon">
    <div class="col-md-8">
    {% if groups.posts.count == 0 %}
        <h2>No post in this group yet!</h2>
    {% else %}
        {% for post in groups.posts.all %}
            {% include 'post/_post.html' %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

TechBuzzy_project/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}

{% load bootstrap4 %}

{% block groupcontent %}
<div class="groupform">
<div class="container">
        <h3 class="title">Create Group</h3>
        <form method="POST" action="{% url 'groups:create' %}" class="formtext">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-success btn-large">Create</button>
            {% endbuttons %}
        </form>
</div>
</div>


{% endblock %}

TechBuzzy_project/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<style>
    .groupcontent{
     box-shadow: 0 15px 25px rgba(0,0,0,.6);
     padding: 20px 20px 20px 20px;
     border-radius: 10px;
     width:600px;
     background: rgba(0,0,0,.5);
     box-sizing: border-box;
     text-color:white;
     position:absolute;
     left:10%;
     font-family: 'Varela Round', serif;
     color:white;
   }
</style>
<div class="groupcontent">
    <div class="col-md-10">
        <div class="">
            {% if user.is_authenticated %}
                <h1 class="mb-3 w-40">
                    <strong>Welcome</strong> <a href="{% url 'post:for_user' username=user.username %}">@{{user.username}}</a>
                </h1>
            {% endif %}
            <h3>Groups</h3>
            <p>Select a Group with a shared interest!</p>
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class="btn btn-success" role="button"><span class="fa fa-plus"></span>Create Group</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block groupcontent %}
<style>
    .pos{
    position:absolute;
    left:50%;
    top:20%;
    width:900px;
    }

</style>
<div class="pos">
    <div class="col-md-8 ">
        <div class="list-group ">
            {% for group in object_list %}
                <a class="list-group-item list-group-item-action flex-column list-group-item-dark align-item-start" href="{% url 'groups:single' slug=group.slug %}">
                    <h3 class="mb-1">{{group.name}}</h3>
                    <p class="mb-2">{{group.description|safe}}</p>
                    <div class="w-40 d-flex justify-content-between">
                        <small class="text-muted">member: <span class="badge badge-pill badge-dark">{{ group.members.count }}</span></small>
                        <small class="text-muted">post: <span class="badge badge-pill badge-dark">{{ group.posts.count }}</span></small>
                        <span></span><span></span>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}