TechBuzzy_project/TechBuzzy_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls',namespace='account')),
    path('account/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('post.urls',namespace='post')),
]

TechBuzzy_project/account/urls.py
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path
from .views import SignUp

app_name = 'account'

urlpatterns = [
    path('login/',LoginView.as_view(template_name = 'account/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',SignUp.as_view(),name='signup'),
]

TechBuzzy_project/post/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.PostCreateView.as_view(),name='create'),
    path('by/<username>/',views.UserPostList.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetailView.as_view(),name='single'),
    path('delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete'),
]

TechBuzzy_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TechBuzzy</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- For Glyhicon -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Cinzel:wght@700&family=Julius+Sans+One&family=Lobster&family=Lora:wght@500&family=Merienda+One&family=Russo+One&display=swap" rel="stylesheet"></head>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
<body>

      <nav class="navbar navbar-expand-lg navbar-dark mynav navcolor navfont" role="navigation" id="navbar">
       <div class="container-fluid">
         <ul class="nav navbar-nav">
           <a class="navbar-brand brandname" href="{% url 'home' %}">TechBuzzy</a>
         </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li><a class="nav-item nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
            <li><a class="nav-item nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
            <li><a class="nav-item nav-link" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
            <li><a class="nav-item nav-link" href="{% url 'account:logout' %}" class="btn btn-simple">Logout</a></li>
          {% else %}
            <li><a class="nav-item nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
            <li><a class="nav-item nav-link" href="{% url 'account:login' %}" class="btn btn-simple">Login</a></li>
            <li><a class="nav-item nav-link" href="{% url 'account:signup' %}" class="btn btn-simple">SignUp</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mycontent ">
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

TechBuzzy_project/templates/home.html
{% extends 'base.html' %}

{% block content %}
<style>
    .welcome{
     box-shadow: 0 15px 25px rgba(0,0,0,.6);
     color:white;
     padding: 20px 20px 20px 20px;
     border-radius: 10px;
     width:700px;
     position:absolute;
     top:20%;
     left:28%;
     background: rgba(0,0,0,.5);
}
</style>
<div class="welcome">
    <h1 class="weltitle"><strong>Welcome</strong></h1>
    <h4 class="buzzy">TechBuzzy</h4>
    <p><i>Technology is best when it brings people together</i></p>
</div>

{% endblock %}

TechBuzzy_project/templates/test.html
{% extends 'base.html' %}

{% block content %}

<br><br><br><br>
<div class="thanks">
<h1 class="buzzy"><strong>You are noe logged in!</strong></h1>
</div>
{% endblock %}

TechBuzzy_project/templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="thanks">
<h1 class="weltitle"><strong>Thanks for visiting!</strong></h1>
</div>
{% endblock %}